theme = ["github.com/dzello/reveal-hugo"]
baseURL = 'https://shuosc.github.io/slides'
canonifyURLs = true  # Fix GitHub Pages wrong path

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.tableOfContents]
startLevel = 1
endLevel = 4

[markup.goldmark.renderer]
unsafe = true

[minify]
disableHTML = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
